services:

# service redis
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

# graphic interface
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
